services:
- postgresql
addons:
  postgresql: '9.6'
before_script:
- cp config/database.yml.travis config/database.yml
language: ruby
rvm:
- 2.7.1
script:
- bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: tLIGnFezjyZ79QrmbvH47A2rfrUFCEoYegUeh3EDQFXZSqqWeA7WvL5rtfXt66NqxGXdwtIGK2e65AzNJ3pFZWspXnUeOeVfErWSVLS3Up/3u7i2G0aAUhrI7RwbjNUBO8nPPPW/uuCpzCZ44VPdYR6MlPBwl1NWQf3CD+JBcS8XlHRpAYSJbrQX+4X9qiQCQ/AqdGfMfa5VAPkzJkH6G6wfZNUy0J8pNqHE16AFucIDvWKqtKldchb+KWIA+fzRz9/xCcWYIgM9CMz3SBHl2wFUUdfxhnHSKUc2i78uLa8DDARH03C8ZOTwTlaf/5Pkw62WwnuuUKvzNEWldSOmJIkV4Mhjlb+As/HUa3PdIoOH0rN8Sg9QqzeN9abfa8h36xcnQrm8AMzpLJM/ok7KXbXQbnxJtfl81CsiwOROq2pXixSsLkq/CaHDu4qY0zULC1hZibtY7OeJz5XBIoOmyNhceUsCLAXaVgpWnM0deUOgEkn2Yndkev9MSFUjjXJC3pSmgSt5ISeWBLlZmgMKIeQvCr9lP5rZXjQBvZ4IOvU671PN5Td9wyt8SwEyOXGUJNBsmSmayGKxlwiaU45gk8mxgaXPF9Vioa4aSZz866jYjDkeRqQ8bE5tub8JTD0jFMj3D5sRHgO20+ahBSKfztvoUw17/iMUezsDm29Skag=
  app:
    master: lit-hollows-59869
  run: rake db:migrate:reset
